version: 1
disable_existing_loggers: true

formatters:
  default:
    format: "%(asctime)s [%(threadName)s] [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default

  mqtt:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/mqtt.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 9

  api_rest:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/api-rest.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 9

  app:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/app.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 9

root:
  level: WARN
  handlers: [app]

loggers:
  server.app:
    level: INFO
    handlers: [app]
    propagate: no

  server.interfaces.mqtt:
      level: INFO
      handlers: [mqtt]
      propagate: no

  server.relays_manager:
      level: INFO
      handlers: [app]
      propagate: no

  server.rest_api:
      level: INFO
      handlers: [api_rest]
      propagate: no
