API_TITLE: RELAYS MANAGER
API_VERSION: v1

# openapi.json version and URL prefix
OPENAPI_VERSION: 3.0.3
OPENAPI_URL_PREFIX: /

# Enable swagger UI
OPENAPI_SWAGGER_UI_PATH: /docs
OPENAPI_SWAGGER_UI_URL: https://cdn.jsdelivr.net/npm/swagger-ui-dist/

# MQTT CONFIGURATION
# TODO: localhost?
MQTT_BROKER_ADDRESS: 192.168.1.16
MQTT_USERNAME: relays_manager"
MQTT_PASSWORD: lamp
MQTT_COMMAND_RELAYS_TOPIC: command/relays
MQTT_RELAYS_STATUS_TOPIC: status/relays
MQTT_QOS: 1
MQTT_MAX_CONNECTION_RETRIES: 12
MQTT_RECONNECTION_TIMEOUT_IN_SEG: 1
MQTT_MSG_PUBLISH_TIMEOUT_IN_SECS: 5
